// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trader.Infrastructure.Persistence;

#nullable disable

namespace Trader.Infrastructure.Migrations
{
    [DbContext(typeof(TraderDbContext))]
    [Migration("20260706193218_AddScalperGttLossProfitEnabled")]
    partial class AddScalperGttLossProfitEnabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Trader.Domain.Entities.Bot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.HasIndex("UserId");

                    b.ToTable("Bots");
                });

            modelBuilder.Entity("Trader.Domain.Entities.BrokerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessTokenProtected")
                        .HasColumnType("longtext");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("BrokerName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("ConnectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalUserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RefreshTokenProtected")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("TokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BrokerName")
                        .IsUnique();

                    b.ToTable("BrokerAccounts");
                });

            modelBuilder.Entity("Trader.Domain.Entities.DemoPaperBuyLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("BoughtAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ContractsRemaining")
                        .HasColumnType("int");

                    b.Property<string>("InstrumentToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "InstrumentToken", "BoughtAtUtc");

                    b.ToTable("DemoPaperBuyLegs");
                });

            modelBuilder.Entity("Trader.Domain.Entities.DemoPaperPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("InstrumentToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("OpenContracts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "InstrumentToken")
                        .IsUnique();

                    b.ToTable("DemoPaperPositions");
                });

            modelBuilder.Entity("Trader.Domain.Entities.DemoPaperTradeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CashFlowInr")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Contracts")
                        .HasColumnType("int");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset>("ExecutedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InstrumentToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("LastPrice")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<int>("LotSize")
                        .HasColumnType("int");

                    b.Property<int>("OpenContractsAfter")
                        .HasColumnType("int");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Tradingsymbol")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("WalletBalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExecutedAtUtc");

                    b.ToTable("DemoPaperTradeLogs");
                });

            modelBuilder.Entity("Trader.Domain.Entities.EmailOtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FailedVerifyAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail", "IsConsumed");

                    b.ToTable("EmailOtpChallenges");
                });

            modelBuilder.Entity("Trader.Domain.Entities.HistoricalCandle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Close")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("High")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("InstrumentToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("Low")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("Open")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentToken", "TimestampUtc");

                    b.HasIndex("InstrumentToken", "Timeframe", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("HistoricalCandles");
                });

            modelBuilder.Entity("Trader.Domain.Entities.KiteFavoriteInstrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Expiry")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("InstrumentToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("InstrumentType")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("LotSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Segment")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal?>("Strike")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("Tradingsymbol")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "InstrumentToken")
                        .IsUnique();

                    b.ToTable("KiteFavoriteInstruments");
                });

            modelBuilder.Entity("Trader.Domain.Entities.KiteTradingLockInstrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Expiry")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("InstrumentToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("InstrumentType")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("LotSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Segment")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal?>("Strike")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("Tradingsymbol")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "InstrumentToken")
                        .IsUnique();

                    b.ToTable("KiteTradingLockInstruments");
                });

            modelBuilder.Entity("Trader.Domain.Entities.MlFavoriteEodReportSent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ReportDayYmd")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ReportDayYmd")
                        .IsUnique();

                    b.ToTable("MlFavoriteEodReportsSent");
                });

            modelBuilder.Entity("Trader.Domain.Entities.MlLightGbmTripleBarrierPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CensorReason")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("EngineModelId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("InstrumentToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<sbyte?>("LabelN3")
                        .HasColumnType("tinyint");

                    b.Property<sbyte?>("LabelN5")
                        .HasColumnType("tinyint");

                    b.Property<sbyte?>("LabelNextBar")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("LabelThresholdFractionApplied")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset?>("NextBarTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("NextBarTimeUtcN3")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("NextBarTimeUtcN5")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("NextClose")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("NextCloseN3")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("NextCloseN5")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("NextOpen")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset>("PredictedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("RefBarTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("RefClose")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "InstrumentToken", "Interval", "PredictedAtUtc");

                    b.ToTable("MlLightGbmTripleBarrierPredictions");
                });

            modelBuilder.Entity("Trader.Domain.Entities.MlPriceDirectionPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CensorReason")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("EngineModelId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("InstrumentToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<sbyte?>("LabelN3")
                        .HasColumnType("tinyint");

                    b.Property<sbyte?>("LabelN5")
                        .HasColumnType("tinyint");

                    b.Property<sbyte?>("LabelNextBar")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("LabelThresholdFractionApplied")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset?>("NextBarTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("NextBarTimeUtcN3")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("NextBarTimeUtcN5")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("NextClose")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("NextCloseN3")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("NextCloseN5")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("NextOpen")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset>("PredictedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("RefBarTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("RefClose")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "InstrumentToken", "Interval", "PredictedAtUtc");

                    b.ToTable("MlPriceDirectionPredictions");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BotId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("RealizedPnl")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("Trader.Domain.Entities.TradingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BotId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.ToTable("TradingOrders");
                });

            modelBuilder.Entity("Trader.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DemoAutoTradeEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("DemoAutoTradeStrategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("equal_split");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<DateTimeOffset?>("EmailVerificationExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("EmailVerifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("FavoriteMlAutomationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("FavoriteMlAutomationInterval")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset?>("FavoriteMlAutomationLastNewPassUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FavoriteMlAutomationMinSecondsAfterBarOpen")
                        .HasColumnType("int");

                    b.Property<int?>("FavoriteMlAutomationPollIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<string>("KiteInstrumentsChartGraphType")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("KiteInstrumentsChartInterval")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("KiteInstrumentsChartIntervalByInstrumentTokenJson")
                        .HasColumnType("longtext");

                    b.Property<string>("KiteInstrumentsChartRangePreset")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("KiteInstrumentsChartZoomJson")
                        .HasColumnType("longtext");

                    b.Property<string>("KiteInstrumentsTrendAnalysisIntervalsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset?>("PasswordResetExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ScalperGraphType")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("ScalperGttEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("ScalperGttLossEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("ScalperGttProfitEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("ScalperInterval")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ScalperRangePreset")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("ScalperSafeModeEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("ScalperSafeStopLossPoints")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScalperSafeTriggerPoints")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("ScalperShowVolume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<byte>("SecondFactorMethod")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("TotpPendingSecretProtected")
                        .HasColumnType("longtext");

                    b.Property<string>("TotpRecoveryCodesProtected")
                        .HasColumnType("longtext");

                    b.Property<string>("TotpSecretProtected")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("WalletBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmailVerificationTokenHash")
                        .IsUnique();

                    b.HasIndex("PasswordResetTokenHash")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Trader.Domain.Entities.UserLoginAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ForwardedFor")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IpInfoJson")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("LoggedInAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LoggedInAtUtc");

                    b.ToTable("UserLoginAudits");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Bot", b =>
                {
                    b.HasOne("Trader.Domain.Entities.Strategy", "Strategy")
                        .WithMany("Bots")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("Bots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.BrokerAccount", b =>
                {
                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("BrokerAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.DemoPaperBuyLeg", b =>
                {
                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("DemoPaperBuyLegs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.DemoPaperPosition", b =>
                {
                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("DemoPaperPositions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.DemoPaperTradeLog", b =>
                {
                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("DemoPaperTradeLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.KiteFavoriteInstrument", b =>
                {
                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("KiteFavoriteInstruments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.KiteTradingLockInstrument", b =>
                {
                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("KiteTradingLockInstruments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.MlFavoriteEodReportSent", b =>
                {
                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("MlFavoriteEodReportsSent")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.MlLightGbmTripleBarrierPrediction", b =>
                {
                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("MlLightGbmTripleBarrierPredictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.MlPriceDirectionPrediction", b =>
                {
                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("MlPriceDirectionPredictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Strategy", b =>
                {
                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("Strategies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Trade", b =>
                {
                    b.HasOne("Trader.Domain.Entities.Bot", "Bot")
                        .WithMany("Trades")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("Trader.Domain.Entities.TradingOrder", b =>
                {
                    b.HasOne("Trader.Domain.Entities.Bot", "Bot")
                        .WithMany("Orders")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("Trader.Domain.Entities.UserLoginAudit", b =>
                {
                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("LoginAudits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Bot", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Strategy", b =>
                {
                    b.Navigation("Bots");
                });

            modelBuilder.Entity("Trader.Domain.Entities.User", b =>
                {
                    b.Navigation("Bots");

                    b.Navigation("BrokerAccounts");

                    b.Navigation("DemoPaperBuyLegs");

                    b.Navigation("DemoPaperPositions");

                    b.Navigation("DemoPaperTradeLogs");

                    b.Navigation("KiteFavoriteInstruments");

                    b.Navigation("KiteTradingLockInstruments");

                    b.Navigation("LoginAudits");

                    b.Navigation("MlFavoriteEodReportsSent");

                    b.Navigation("MlLightGbmTripleBarrierPredictions");

                    b.Navigation("MlPriceDirectionPredictions");

                    b.Navigation("Strategies");
                });
#pragma warning restore 612, 618
        }
    }
}
