// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trader.Infrastructure.Persistence;

#nullable disable

namespace Trader.Infrastructure.Migrations
{
    [DbContext(typeof(TraderDbContext))]
    [Migration("20260506210000_AddKiteInstrumentsChartSettings")]
    partial class AddKiteInstrumentsChartSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Trader.Domain.Entities.Bot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.HasIndex("UserId");

                    b.ToTable("Bots");
                });

            modelBuilder.Entity("Trader.Domain.Entities.EmailOtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FailedVerifyAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail", "IsConsumed");

                    b.ToTable("EmailOtpChallenges");
                });

            modelBuilder.Entity("Trader.Domain.Entities.KiteFavoriteInstrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Expiry")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("InstrumentToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("InstrumentType")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("LotSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Segment")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal?>("Strike")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("Tradingsymbol")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "InstrumentToken")
                        .IsUnique();

                    b.ToTable("KiteFavoriteInstruments");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BotId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("RealizedPnl")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("Trader.Domain.Entities.TradingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BotId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.ToTable("TradingOrders");
                });

            modelBuilder.Entity("Trader.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("BrokerConnectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BrokerProvider")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<DateTimeOffset?>("EmailVerificationExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("EmailVerifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KiteAccessTokenProtected")
                        .HasColumnType("longtext");

                    b.Property<string>("KiteRefreshTokenProtected")
                        .HasColumnType("longtext");

                    b.Property<string>("KiteUserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("KiteInstrumentsChartGraphType")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("KiteInstrumentsChartInterval")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("KiteInstrumentsChartRangePreset")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset?>("PasswordResetExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<byte>("SecondFactorMethod")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("TotpPendingSecretProtected")
                        .HasColumnType("longtext");

                    b.Property<string>("TotpRecoveryCodesProtected")
                        .HasColumnType("longtext");

                    b.Property<string>("TotpSecretProtected")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmailVerificationTokenHash")
                        .IsUnique();

                    b.HasIndex("PasswordResetTokenHash")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Bot", b =>
                {
                    b.HasOne("Trader.Domain.Entities.Strategy", "Strategy")
                        .WithMany("Bots")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("Bots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Strategy", b =>
                {
                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("Strategies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Trade", b =>
                {
                    b.HasOne("Trader.Domain.Entities.Bot", "Bot")
                        .WithMany("Trades")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("Trader.Domain.Entities.TradingOrder", b =>
                {
                    b.HasOne("Trader.Domain.Entities.Bot", "Bot")
                        .WithMany("Orders")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("Trader.Domain.Entities.KiteFavoriteInstrument", b =>
                {
                    b.HasOne("Trader.Domain.Entities.User", "User")
                        .WithMany("KiteFavoriteInstruments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Bot", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Trader.Domain.Entities.Strategy", b =>
                {
                    b.Navigation("Bots");
                });

            modelBuilder.Entity("Trader.Domain.Entities.User", b =>
                {
                    b.Navigation("Bots");

                    b.Navigation("KiteFavoriteInstruments");

                    b.Navigation("Strategies");
                });
#pragma warning restore 612, 618
        }
    }
}
