FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY Trader.sln ./
COPY src/ ./src/
COPY tests/ ./tests/
RUN dotnet publish src/Trader.Api/Trader.Api.csproj -c Release -o /app/publish -r linux-x64 --self-contained false /p:RunEfMigrationsOnBuild=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
ENTRYPOINT ["dotnet", "Trader.Api.dll"]
